import { Injectable, signal, isDevMode } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { lastValueFrom } from 'rxjs';

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
}

export interface GeminiProxyResponse {
  reply?: string;
  error?: string;
}

// Convert our simple UI role structure to Gemini API history structure
export interface GeminiApiMessage {
  role: 'user' | 'model';
  parts: { text: string }[];
}

@Injectable({
  providedIn: 'root',
})
export class GeminiService {
  public messages = signal<ChatMessage[]>([]);
  public isTyping = signal<boolean>(false);
  public isInitialized = signal<boolean>(false);

  private systemInstruction: string = '';
  // Point to the relative API path. In dev mode this could require an Angular proxy,
  // but for Vercel it works automatically relative to the site root.
  // To test locally without Vercel CLI, we will handle a simulated fallback or point directly to the function if running `vercel dev`.
  private apiUrl = '/api/gemini';

  constructor(private http: HttpClient) {
    this.initializeChatSession();
  }

  private initializeChatSession() {
    this.http.get('/assets/data/PROFESSIONAL_CONTEXT.json').subscribe({
      next: (contextData: any) => {
        this.systemInstruction = `
        You are an AI assistant representing Agustín Roel on his personal portfolio website. 
        Your goal is to answer questions from recruiters, clients, and visitors using the EXACT information provided in the following professional context JSON.
        You must act as a knowledgeable, polite, and helpful clone. Be concise, direct, and professional.
        If asked something outside of this context, politely explain that you are an AI assistant limited to providing information about Agustín's professional profile, and suggest they contact him directly for other inquiries.
        
        Context Data (JSON format):
        ${JSON.stringify(contextData)}
        `;

        this.messages.set([
          {
            role: 'model',
            text: '¡Hola! Soy el asistente virtual de Agustín. ¿En qué te puedo ayudar hoy? Puedo responder preguntas sobre su experiencia, stack tecnológico o proyectos.',
          },
        ]);

        this.isInitialized.set(true);
      },
      error: (err) => {
        console.error('Failed to load professional context for Gemini', err);
        this.messages.set([
          {
            role: 'model',
            text: 'No se pudo cargar el archivo PROFESIONAL_CONTEXT.json. Revisa que exista en public/assets/data/.',
          },
        ]);
        this.isInitialized.set(true);
      },
    });
  }

  // Build the history array in the exact format the Gemini SDK expects
  private buildHistory(): GeminiApiMessage[] {
    // Skip the very first "greeting" message because it was not generated by the actual model session
    const chatHistory = this.messages().slice(1);
    return chatHistory.map((msg) => ({
      role: msg.role,
      parts: [{ text: msg.text }],
    }));
  }

  public async sendMessage(userMessage: string) {
    // Add user message to UI immediately
    this.messages.update((msgs) => [...msgs, { role: 'user', text: userMessage }]);
    this.isTyping.set(true);

    const history = this.buildHistory();
    // Exclude the current user message from the history array before sending
    history.pop();

    try {
      const response = await lastValueFrom(
        this.http.post<GeminiProxyResponse>(this.apiUrl, {
          message: userMessage,
          history: history,
          systemInstruction: this.systemInstruction,
        }),
      );

      if (response && response.reply) {
        this.messages.update((msgs) => [...msgs, { role: 'model', text: response.reply! }]);
      } else if (response && response.error) {
        throw new Error(response.error);
      }
    } catch (error) {
      console.error('Error contacting Gemini Backend Proxy:', error);
      this.messages.update((msgs) => [
        ...msgs,
        {
          role: 'model',
          text: 'Ups, parece que hubo un error de conexión con el servidor. ¿Configuraste GEMINI_API_KEY en Vercel?',
        },
      ]);
    } finally {
      this.isTyping.set(false);
    }
  }
}
